[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20" # or whatever version your contract needs

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
